'use client';
import {useEffect,useState} from 'react';
import {Heart,CalendarDays,Mail,ExternalLink,MapPin,Check,Plus,Bookmark,Bell,Link as LinkIcon,LoaderCircle,Settings2} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Switch} from '@/components/ui/switch';
import {categories,seedEvents,activeEvents,type EventRecord} from '@/lib/catalog';
type Prefs={events:string[];providers:string[];categories:string[];booked:string[];emailEnabled:boolean};
type ApiResponse={error?:string;events:EventRecord[];preferences:Prefs;emailReady:boolean;calendarSubscriptionReady:boolean;email:string;calendarToken:string|null};
const empty:Prefs={events:[],providers:[],categories:[],booked:[],emailEnabled:false};
const statusLabels={open:'预约入口已公布',announced:'预约信息待确认',no_booking:'无需预约',sold_out:'暂时约满',cancelled:'已取消'};
function match(p:Prefs,e:EventRecord){return p.events.includes(e.id)||p.providers.includes(e.provider)||p.categories.includes(e.category);}
async function json(url:string,options?:RequestInit){const r=await fetch(url,options);const d=await r.json() as ApiResponse;if(!r.ok)throw new Error(d.error??'请求失败，请重试');return d;}
export default function Home(){
 const [events,setEvents]=useState(activeEvents(seedEvents)),[prefs,setPrefs]=useState<Prefs>(empty),[category,setCategory]=useState('all'),[view,setView]=useState('discover'),[ready,setReady]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[email,setEmail]=useState(''),[mailReady,setMailReady]=useState(false),[subscriptionReady,setSubscriptionReady]=useState(false),[token,setToken]=useState<string|null>(null),[expanded,setExpanded]=useState<string|null>(null),[url,setUrl]=useState(''),[submitting,setSubmitting]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let live=true;setReady(false);Promise.all([json('/api/catalog'),json('/api/preferences')]).then(([c,p])=>{if(!live)return;setEvents(c.events);setMailReady(c.emailReady);setSubscriptionReady(c.calendarSubscriptionReady);setPrefs(p.preferences);setEmail(p.email);setToken(p.calendarToken);setReady(true);setError('');}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[refresh]);
 async function save(p:Prefs){if(!ready||saving)return;setSaving(true);setError('');try{const d=await json('/api/preferences',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});setPrefs(d.preferences);setToken(d.calendarToken);setMessage('已保存');return d.preferences;}catch(e){setError((e as Error).message);throw e;}finally{setSaving(false)}}
 const toggle=(key:'events'|'providers'|'categories'|'booked',id:string)=>save({...prefs,[key]:prefs[key].includes(id)?prefs[key].filter(v=>v!==id):[...prefs[key],id]}).catch(()=>{});
 useEffect(()=>{const doc=document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}};if(!doc.modelContext?.registerTool)return;const controller=new AbortController();doc.modelContext.registerTool({name:'list_free_activities',description:'读取当前巴黎免费活动及关注状态。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({events:events.map(e=>({id:e.id,title:e.title,category:e.category,status:e.status,followed:match(prefs,e)}))})},{signal:controller.signal});return()=>controller.abort()},[events,prefs]);
 const followed=events.filter(e=>match(prefs,e)),display=events.filter(e=>(category==='all'||e.category===category)&&(view!=='following'||match(prefs,e)));
 const bookingEvents=followed.filter(e=>e.bookingOpensAt&&!prefs.booked.includes(e.id)),providers=[...new Set(events.map(e=>e.provider))];
 const last=events.reduce((v,e)=>e.verifiedAt>v?e.verifiedAt:v,'');
 async function submit(e:React.FormEvent){e.preventDefault();setSubmitting(true);try{await json('/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});setUrl('');setMessage('链接已提交，核实后收录。')}catch(e){setError((e as Error).message)}finally{setSubmitting(false)}}
 function download(mode:'booking'|'visit'){window.location.href='/api/calendar?mode='+mode;}
 return <div className="shell">
 <header className="topbar"><a className="brand" href="/"><span className="brandmark">0<span>€</span></span><div><strong>巴黎葛朗台</strong><small>PARIS GRATUIT</small></div></a><div className="topnote">把钱留给喜欢的事</div><Button variant="outline" className="nav-settings" onClick={()=>setView('reminders')}><Bell size={16}/> 提醒设置</Button></header>
 <div className="workspace"><aside className="sidebar"><p className="nav-label">发现巴黎</p><Button variant="ghost" className={'nav-item '+(view==='discover'?'selected':'')} onClick={()=>setView('discover')}><span>◎</span>全部活动<span className="count">{events.length}</span></Button><Button variant="ghost" className={'nav-item '+(view==='following'?'selected':'')} onClick={()=>setView('following')}><Heart/>我的关注<span className="count">{followed.length}</span></Button><Button variant="ghost" className={'nav-item '+(view==='reminders'?'selected':'')} onClick={()=>setView('reminders')}><Bell/>我的提醒</Button><div className="nav-divider"/><p className="nav-label">四种免费的快乐</p>{categories.map(c=><Button variant="ghost" key={c.id} className={'nav-item '+(category===c.id&&view!=='reminders'?'selected':'')} onClick={()=>{setCategory(c.id);setView('discover')}}><span>{c.icon}</span>{c.name}<span className="count">{events.filter(e=>e.category===c.id).length}</span></Button>)}<div className="sidebar-bottom"><span className="edition">PARIS · ÎLE-DE-FRANCE</span><p>免费入场 ≠ 免费消费<br/>每条活动都标明条件。</p><small>来源核实 · {last?new Date(last).toLocaleDateString('zh-CN',{timeZone:'Europe/Paris'}):'待更新'}</small></div></aside>
 <main><div className="page-heading"><div><p className="eyebrow">PARIS, SANS DÉPENSER</p><h1>{view==='following'?'你的免费好去处':view==='reminders'?'让好活动来找你':'巴黎的快乐，可以免费。'}</h1><p className="lead">{view==='following'?'关注的活动、场馆和栏目，集中看这里。':view==='reminders'?'关注一次，集中管理开票与日历提醒。':'免费展览、体育、快闪与城市活动，放在同一个地方。'}</p></div><div className="zero-badge"><strong>0€</strong><span>入场，也能很精彩</span></div></div>
 {error&&<div role="alert" className="notice error">{error} <Button size="sm" variant="outline" onClick={()=>setRefresh(v=>v+1)}>重新加载</Button></div>}{message&&<div role="status" className="notice success">{message}<Button variant="ghost" size="sm" onClick={()=>setMessage('')}>关闭</Button></div>}
 {view!=='reminders'?<><div className="filterbar"><div className="filtertabs"><Button variant="ghost" className={category==='all'?'active':''} onClick={()=>setCategory('all')}>全部</Button>{categories.map(c=><Button variant="ghost" key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.name}</Button>)}</div><span className="result-count">{display.length} 个活动</span></div>
 <div className="activity-grid">{display.map(e=>{const isFollowed=match(prefs,e),booked=prefs.booked.includes(e.id);return <article key={e.id} className={'activity-card '+e.category}><div className="card-top"><span className="category-tag">{categories.find(c=>c.id===e.category)?.icon} {e.kind}</span><Button variant="ghost" size="icon" disabled={!ready||saving} aria-label={(prefs.events.includes(e.id)?'取消关注':'关注')+e.title} aria-pressed={prefs.events.includes(e.id)} onClick={()=>toggle('events',e.id)}><Heart size={19} fill={isFollowed?'currentColor':'none'} className={isFollowed?'hearted':''}/></Button></div><p className="card-subtitle">{e.subtitle}</p><h2>{e.title}</h2><p className="date"><CalendarDays size={16}/>{e.dateLabel}</p><p className="location"><MapPin size={16}/>{e.location}</p><div className="card-condition"><span className={'status '+e.status}>{booked?'已预约':statusLabels[e.status]}</span><span className="free-label">免费入场</span></div><p className="free-note">{e.freeNote}</p>{expanded===e.id&&<div className="details"><p>{e.description}</p><p>开票时间：{e.bookingOpensAt?new Date(e.bookingOpensAt).toLocaleString('zh-CN',{timeZone:'Europe/Paris'}):e.status==='no_booking'?'无需预约':'尚未确认，不生成开票日历提醒'}</p><p>核实日期：{new Date(e.verifiedAt).toLocaleDateString('zh-CN',{timeZone:'Europe/Paris'})}</p><a href={e.sourceUrl} target="_blank" rel="noreferrer">官方信息 <ExternalLink size={13}/></a>{e.bookingUrl&&<Button size="sm" variant="outline" disabled={!ready||saving} onClick={()=>toggle('booked',e.id)}><Check size={15}/>{booked?'撤销已预约':'标记我已预约'}</Button>}</div>}<div className="card-actions"><Button variant="ghost" onClick={()=>setExpanded(expanded===e.id?null:e.id)}>{expanded===e.id?'收起详情':'活动详情'}</Button><Button asChild className={e.bookingUrl?'primary-btn':'source-btn'} variant={e.bookingUrl?'default':'outline'}><a href={e.bookingUrl??e.sourceUrl} target="_blank" rel="noreferrer">{e.bookingUrl?'官方预约':'查看官方信息'}<ExternalLink size={14}/></a></Button></div></article>})}</div>
 {display.length===0&&<div className="empty"><Bookmark size={32}/><h2>{view==='following'?'还没有关注的活动':'暂时没有已核实的活动'}</h2><p>{view==='following'?'点击活动上的爱心，或在右侧关注场馆。':'新内容核实后会收录。不会用付费活动凑数。'}</p></div>}
 </>:<div className="reminders-grid"><section className="panel"><div className="panel-title"><CalendarDays/><h2>苹果日历</h2></div><p>只把你关注、且已确认开票时间的活动加入提醒。活动日期和开票日期分别导出。</p><div className="calendar-count"><strong>{bookingEvents.length}</strong><span>个已确认开票时间</span></div><Button className="primary-btn wide" disabled={!ready||bookingEvents.length===0} onClick={()=>download('booking')}>导出开票提醒 .ics</Button><Button className="wide" variant="outline" disabled={!ready||!followed.some(e=>e.startDate===e.endDate&&e.startDate)} onClick={()=>download('visit')}>导出单日活动日期 .ics</Button><p className="help">下载后打开文件，可导入苹果日历。导入文件不会自动更新；尚未公布时间的活动不编造提醒。</p>{subscriptionReady&&token?<Button asChild variant="outline" className="wide"><a href={'webcal://'+(typeof window!=='undefined'?window.location.host:'')+'/api/calendar?token='+token}>订阅开票日历</a></Button>:<div className="connection-note">自动订阅尚未启用。当前私人网站需要登录，苹果日历不能直接读取。</div>}</section><section className="panel"><div className="panel-title"><Mail/><h2>开票邮件</h2></div><p>只通知你关注的活动。标记“已预约”后停止该活动的预约提醒。</p><div className="setting-row"><div><strong>开票时发邮件</strong><small>{mailReady?'仅发送预约提醒，不发送广告':'邮件服务尚未连接'}</small></div><Switch aria-label="开票时发邮件" checked={prefs.emailEnabled} disabled={!ready||saving||!mailReady} onCheckedChange={v=>save({...prefs,emailEnabled:v}).catch(()=>{})}/></div><label className="field-label">接收邮箱</label><Input value={email} readOnly aria-label="接收邮箱" placeholder="登录后显示你的邮箱"/><p className="help">使用当前登录账号的邮箱。</p>{!mailReady&&<div className="connection-note">需要接入邮件发送服务和验证发信地址后，才能启用。</div>}<div className="quiet-card"><Check size={17}/><div><strong>少一点邮件，多一点生活</strong><p>同一活动的开票通知只发一次；取消关注即可停止该活动的提醒。</p></div></div></section><section className="panel span-two"><h2>关注中的预约活动</h2>{followed.filter(e=>e.bookingUrl&&!prefs.booked.includes(e.id)).map(e=><div className="reminder-item" key={e.id}><div><strong>{e.title}</strong><small>{e.bookingOpensAt?new Date(e.bookingOpensAt).toLocaleString('zh-CN',{timeZone:'Europe/Paris'}):'具体开票时间待确认'}</small></div><span className={'status '+e.status}>{statusLabels[e.status]}</span></div>)}{!followed.some(e=>e.bookingUrl)&&<p className="help">先关注一个需要预约的活动。</p>}</section></div>}
 <footer>信息以主办方最新公告为准 · 所有时间按巴黎当地时间显示 · 社交平台线索核实后收录</footer></main>
 <aside className="rightbar"><section className="follow-panel"><div className="panel-title"><Heart size={19}/><h2>关注你喜欢的</h2></div><p className="help">关注场馆或栏目，新收录的匹配活动也会出现在“我的关注”。</p><p className="section-label">按栏目关注</p>{categories.map(c=><div className="follow-row" key={c.id}><span>{c.icon} {c.name}</span><Switch aria-label={'关注'+c.name} checked={prefs.categories.includes(c.id)} disabled={!ready||saving} onCheckedChange={()=>toggle('categories',c.id)}/></div>)}<p className="section-label">按场馆 / 主办方关注</p>{providers.map(p=><div className="provider-row" key={p}><span>{p}</span><Button size="icon-sm" variant="outline" disabled={!ready||saving} aria-label={(prefs.providers.includes(p)?'取消关注':'关注')+p} aria-pressed={prefs.providers.includes(p)} onClick={()=>toggle('providers',p)}>{prefs.providers.includes(p)?<Check size={15}/>:<Plus size={15}/>}</Button></div>)}{saving&&<p className="help">正在保存…</p>}</section><section className="weekly-card"><span className="section-label">集中更新</span><h3>把订阅变成一份清单</h3><p>每周发现新活动，开票信息单独核实。已公布预约入口不保证仍有余票。</p><Button variant="outline" className="wide" onClick={()=>setView('reminders')}><Settings2 size={15}/>管理我的提醒</Button></section><section className="submit-card"><div className="panel-title"><LinkIcon size={18}/><h2>刷到了好活动？</h2></div><p className="help">提交官网、Instagram 或 TikTok 的公开链接，核实后收录。</p><form onSubmit={submit}><Input type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…" aria-label="活动链接"/><Button className="wide" variant="outline" type="submit" disabled={!ready||submitting}>{submitting?<LoaderCircle className="spin" size={16}/>:'提交活动链接'}</Button></form></section></aside></div></div>
}
