export type Category = 'exhibitions'|'sports'|'popup'|'other';
export type EventRecord={id:string;category:Category;title:string;subtitle:string;provider:string;location:string;startDate:string|null;endDate:string|null;dateLabel:string;status:'open'|'announced'|'no_booking'|'sold_out'|'cancelled';bookingOpensAt:string|null;description:string;freeNote:string;sourceUrl:string;bookingUrl:string|null;kind:string;verifiedAt:string};
export const categories = [{id:'exhibitions',name:'免费展览',icon:'🖼️'},{id:'sports',name:'免费体育赛事',icon:'🏅'},{id:'popup',name:'免费 Pop-up',icon:'🛍️'},{id:'other',name:'其他免费活动',icon:'🎉'}] as const;
export const seedEvents:EventRecord[] = [
  {
    "id": "19m-michel-2026",
    "category": "exhibitions",
    "title": "19M · 帽子的变形记",
    "subtitle": "Métamorphoses · Maison Michel",
    "provider": "le19M",
    "location": "2 place Skanderbeg · 19区",
    "startDate": "2026-09-23",
    "endDate": "2026-12-13",
    "dateLabel": "9月23日 — 12月13日",
    "status": "open",
    "bookingOpensAt": null,
    "description": "走进 Maison Michel 的帽饰工艺世界。周三至周日 11:00–18:30；免费参观需要预约，余票以官方页面为准。",
    "freeNote": "展览免费；部分独立工作坊可能收费。",
    "sourceUrl": "https://www.le19m.com/fr/agenda/metamorphoses-chapeaux-maison-michel",
    "bookingUrl": "https://billetterie.le19m.com/list/events?orderBy=TYPE",
    "kind": "临时展览",
    "verifiedAt": "2026-10-08T13:52:00Z"
  },
  {
    "id": "orsay-nov-2026",
    "category": "exhibitions",
    "title": "奥赛 · 每月首个周日免费",
    "subtitle": "Musée d’Orsay",
    "provider": "Musée d’Orsay",
    "location": "Esplanade Valéry Giscard d’Estaing · 7区",
    "startDate": "2026-11-01",
    "endDate": "2026-11-01",
    "dateLabel": "11月1日 · 周日",
    "status": "open",
    "bookingOpensAt": null,
    "description": "免费日包含常设藏品和当天临时展览，需要提前预约时段。11月1日的预约入口已公布；可选时段以票务官网为准。",
    "freeNote": "当日对所有人免费，须取得免费预约票。",
    "sourceUrl": "https://www.musee-orsay.fr/fr/visite/tarifs",
    "bookingUrl": "https://billetterie.musee-orsay.fr/billets-d-entree-au-musee-d-orsay-expo-css5-museeorsay-pg1-rg28911.html",
    "kind": "首个周日",
    "verifiedAt": "2026-10-08T13:52:00Z"
  },
  {
    "id": "louvre-nov-2026",
    "category": "exhibitions",
    "title": "卢浮宫 · 免费夜场",
    "subtitle": "Musée du Louvre",
    "provider": "Musée du Louvre",
    "location": "Rue de Rivoli · 1区",
    "startDate": "2026-11-06",
    "endDate": "2026-11-06",
    "dateLabel": "11月6日 · 周五 18:00–21:00",
    "status": "announced",
    "bookingOpensAt": null,
    "description": "每月首个周五晚免费（7、8月除外）。官网说明通常提前几天放票；11月的具体开票时间尚未核实。",
    "freeNote": "夜场免费，必须预约；不是首个周日。",
    "sourceUrl": "https://www.louvre.fr/expositions-et-evenements/evenements-activites/les-nocturnes-du-mercredi-et-du-vendredi",
    "bookingUrl": "https://www.ticket.louvre.fr/",
    "kind": "免费夜场",
    "verifiedAt": "2026-10-08T13:52:00Z"
  },
  {
    "id": "petit-palais-permanent",
    "category": "exhibitions",
    "title": "小皇宫 · 常设藏品",
    "subtitle": "Petit Palais",
    "provider": "Petit Palais",
    "location": "Avenue Winston-Churchill · 8区",
    "startDate": null,
    "endDate": null,
    "dateLabel": "常年免费 · 开馆日可参观",
    "status": "no_booking",
    "bookingOpensAt": null,
    "description": "常设藏品免费且无需预约。独立临时展览及导览活动须另查价格。",
    "freeNote": "仅常设藏品免费。",
    "sourceUrl": "https://www.petitpalais.paris.fr/visiter/preparer-votre-visite",
    "bookingUrl": null,
    "kind": "常设展览",
    "verifiedAt": "2026-10-08T13:52:00Z"
  },
  {
    "id": "sport-dimanches-2026",
    "category": "sports",
    "title": "Paris Sport Dimanches · 周日运动",
    "subtitle": "免费参加 · 非观赛赛事",
    "provider": "Ville de Paris · 体育",
    "location": "巴黎多个公园与集合点",
    "startDate": "2026-09-27",
    "endDate": "2027-07-04",
    "dateLabel": "每周日 · 10:00–12:00",
    "status": "no_booking",
    "bookingOpensAt": null,
    "description": "市政府组织的免费户外体育活动，无需预先报名。运动项目、集合点及名额以各场地公告为准。",
    "freeNote": "免费参加，不等同于比赛观赛。",
    "sourceUrl": "https://www.paris.fr/evenements/paris-sport-dimanches-faites-du-sport-gratuitement-dans-tout-paris-69235",
    "bookingUrl": null,
    "kind": "体育活动",
    "verifiedAt": "2026-10-08T13:52:00Z"
  },
  {
    "id": "dreamland-popup-2026",
    "category": "popup",
    "title": "Dreamland · 20周年快闪",
    "subtitle": "漫画原稿展与作者见面",
    "provider": "Pika Édition",
    "location": "39 rue Volta · 3区",
    "startDate": "2026-10-16",
    "endDate": "2026-10-19",
    "dateLabel": "10月16日 — 19日 · 10:30–19:00",
    "status": "no_booking",
    "bookingOpensAt": null,
    "description": "四天限定快闪店，展示漫画原稿，并有作者签售。签售的具体参与条件请看主办方公告。",
    "freeNote": "免费入场；书籍和周边需付费。",
    "sourceUrl": "https://www.paris.fr/evenements/un-pop-up-store-dreamland-du-16-au-19-octobre-a-paris-125430",
    "bookingUrl": null,
    "kind": "品牌快闪",
    "verifiedAt": "2026-10-08T13:52:00Z"
  },
  {
    "id": "bande-createurs-oct-2026",
    "category": "popup",
    "title": "Bande de Créateurs · 秋日快闪",
    "subtitle": "80多位法国创作者",
    "provider": "Bande de Créateurs",
    "location": "Bastille Design Center · 11区",
    "startDate": "2026-10-10",
    "endDate": "2026-10-11",
    "dateLabel": "10月10日 — 11日",
    "status": "no_booking",
    "bookingOpensAt": null,
    "description": "插画、首饰、陶瓷与手作品牌的周末快闪。周六 10:00–20:00，周日 10:00–19:00。",
    "freeNote": "入场免费；商品、餐饮另付费。",
    "sourceUrl": "https://www.paris.fr/evenements/bande-de-createur-est-de-retour-cet-automne-125331",
    "bookingUrl": null,
    "kind": "创作者快闪",
    "verifiedAt": "2026-10-08T13:52:00Z"
  },
  {
    "id": "nature-oct-2026",
    "category": "other",
    "title": "Paris Nature · 十月自然活动",
    "subtitle": "散步、工作坊与讲座",
    "provider": "Ville de Paris · 自然",
    "location": "巴黎公园、花园与自然教育场所",
    "startDate": "2026-10-01",
    "endDate": "2026-10-31",
    "dateLabel": "10月 · 各活动日期不同",
    "status": "announced",
    "bookingOpensAt": null,
    "description": "巴黎市提供的免费自然活动合集。请在官方月度节目中选择具体活动；报名方式和名额逐项确认。",
    "freeNote": "节目中的自然活动免费；各项目报名要求不同。",
    "sourceUrl": "https://www.paris.fr/evenements/nature-a-paris-le-programme-13407",
    "bookingUrl": null,
    "kind": "活动合集",
    "verifiedAt": "2026-10-08T13:52:00Z"
  }
];
export function activeEvents(events:EventRecord[],now=new Date()){const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris'}).format(now);return events.filter(e=>e.status!=='cancelled'&&(!e.endDate||e.endDate>=day));}
