import {db,errorResponse,runtime,allEvents} from '@/lib/store';
import {z} from 'zod';import {deliver} from '@/lib/notify';
// This endpoint is protected by owner-private Sites dispatch. For public hosting, UPDATE_SECRET is mandatory.
export function authorized(req:Request){if(runtime.UPDATE_SECRET)return req.headers.get('authorization')==='Bearer '+runtime.UPDATE_SECRET;return runtime.PUBLIC_CALENDAR_ENABLED!=='true';}
const https=z.string().url().refine(v=>new URL(v).protocol==='https:');
const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable();
const item=z.object({id:z.string().regex(/^[a-z0-9-]{1,120}$/),category:z.enum(['exhibitions','sports','popup','other']),title:z.string().min(1).max(150),subtitle:z.string().max(200),provider:z.string().min(1).max(200),location:z.string().max(300),startDate:day,endDate:day,dateLabel:z.string().max(200),status:z.enum(['open','announced','no_booking','sold_out','cancelled']),bookingOpensAt:z.string().datetime({offset:true}).nullable(),description:z.string().max(1800),freeNote:z.string().min(1).max(500),sourceUrl:https,bookingUrl:https.nullable(),kind:z.string().max(100),verifiedAt:z.string().datetime({offset:true})}).refine(e=>!e.startDate||!e.endDate||e.endDate>=e.startDate,'活动结束时间早于开始时间');
export async function GET(req:Request){if(!authorized(req))return Response.json({error:'无权更新'},{status:403});try{return Response.json({events:await allEvents(),submissions:(await db().prepare('SELECT id,url,created_at FROM submissions WHERE reviewed=0 ORDER BY created_at DESC LIMIT 100').all()).results});}catch(e){return errorResponse(e,503);}}
export async function PUT(req:Request){if(!authorized(req))return Response.json({error:'无权更新'},{status:403});try{const body=z.object({events:z.array(item).min(1).max(100),reviewedSubmissionIds:z.array(z.string()).max(100).optional()}).parse(await req.json());if(new Set(body.events.map(e=>e.id)).size!==body.events.length)throw new Error('活动编号重复。');const now=new Date().toISOString();const statements=body.events.map(e=>db().prepare('INSERT INTO events(id,data,updated_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').bind(e.id,JSON.stringify(e),now));for(const id of body.reviewedSubmissionIds??[])statements.push(db().prepare('UPDATE submissions SET reviewed=1 WHERE id=?').bind(id));await db().batch(statements);return Response.json({updated:body.events.length,notifications:await deliver()});}catch(e){return errorResponse(e);}}
